// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdediOYs8SMo_WL2dRuT33qZh4qXGq5o',
    appId: '1:300233413432:web:137e81190f1f85ae4fa7cd',
    messagingSenderId: '300233413432',
    projectId: 'reddit-clone-6330a',
    authDomain: 'reddit-clone-6330a.firebaseapp.com',
    storageBucket: 'reddit-clone-6330a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDFPY1_gng2d0BNe1Ui9ajHzZkHMwe7Y',
    appId: '1:300233413432:android:2b8e21c67fb4f63c4fa7cd',
    messagingSenderId: '300233413432',
    projectId: 'reddit-clone-6330a',
    storageBucket: 'reddit-clone-6330a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpwtS4ghZaAsyg_MgA291nOhnQfPnq9aA',
    appId: '1:300233413432:ios:8f009e12edecdbfb4fa7cd',
    messagingSenderId: '300233413432',
    projectId: 'reddit-clone-6330a',
    storageBucket: 'reddit-clone-6330a.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
